import 'dart:io';

import 'package:csv/csv.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../core/money.dart';
import '../../core/quantity.dart';
import '../models/books.dart';
import '../models/bucket.dart';
import '../models/inventory.dart';
import '../models/txn.dart';

class ReportExporter {
  ReportExporter._();

  static final _dateFmt = DateFormat('yyyy-MM-dd HH:mm');

  /// Builds a CSV containing every field of every transaction.
  static String buildTransactionsCsv(Iterable<Txn> txns) {
    final rows = <List<Object?>>[
      const [
        'Date',
        'Type',
        'Category',
        'Amount (₹)',
        'Payment mode',
        'Party',
        'Notes',
        'Tag',
        'Source',
      ],
      for (final t in txns)
        [
          _dateFmt.format(t.occurredAt),
          t.type,
          t.category,
          Money.toRupees(t.amountPaise),
          t.paymentMode,
          t.partyName ?? '',
          t.notes ?? '',
          t.tag ?? '',
          t.source,
        ],
    ];
    return Csv().encode(rows);
  }

  /// Human-friendly monthly summary — pastes cleanly into WhatsApp / email.
  static String buildMonthlySummaryText({
    required DateTime month,
    required List<Txn> txns,
    required int salaryPaidPaise,
    required int advanceOutstandingPaise,
  }) {
    final title = DateFormat('MMMM yyyy').format(month);
    final income = txns.where((t) => t.isIncome).fold<int>(0, (s, t) => s + t.amountPaise);
    // Salaries are held in a separate ledger (not transactions); include them
    // in total expenses and net so the summary matches the in-app Reports.
    final txnExpense = txns.where((t) => !t.isIncome).fold<int>(0, (s, t) => s + t.amountPaise);
    final expense = txnExpense + salaryPaidPaise;
    final net = income - expense;

    // Category breakdowns
    final expenseByCat = <String, int>{};
    final incomeByCat = <String, int>{};
    for (final t in txns) {
      final map = t.isIncome ? incomeByCat : expenseByCat;
      map.update(t.category, (v) => v + t.amountPaise, ifAbsent: () => t.amountPaise);
    }
    final expenseSorted = expenseByCat.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final incomeSorted = incomeByCat.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    // Payment mode split (expenses)
    var cash = 0;
    var digital = 0;
    for (final t in txns) {
      if (t.isIncome) continue;
      if (t.paymentMode == 'Cash') {
        cash += t.amountPaise;
      } else {
        digital += t.amountPaise;
      }
    }

    final sb = StringBuffer();
    sb.writeln('*Chatori Finance — $title*');
    sb.writeln();
    sb.writeln('💰 Income:   ${Money.format(income)}');
    sb.writeln('💸 Expenses: ${Money.format(expense)}');
    sb.writeln('📊 Net:      ${Money.format(net)}');
    sb.writeln();
    if (salaryPaidPaise > 0 || advanceOutstandingPaise > 0) {
      sb.writeln('👥 Salaries paid:      ${Money.format(salaryPaidPaise)}');
      sb.writeln('🧾 Advances outstanding: ${Money.format(advanceOutstandingPaise)}');
      sb.writeln();
    }
    if (incomeSorted.isNotEmpty) {
      sb.writeln('Income breakdown:');
      for (final e in incomeSorted) {
        sb.writeln('  • ${e.key}: ${Money.format(e.value)}');
      }
      sb.writeln();
    }
    if (expenseSorted.isNotEmpty) {
      sb.writeln('Top expenses:');
      for (final e in expenseSorted.take(6)) {
        sb.writeln('  • ${e.key}: ${Money.format(e.value)}');
      }
      sb.writeln();
    }
    if (expense > 0) {
      sb.writeln('Payment mix: '
          'Cash ${Money.format(cash)} · Digital ${Money.format(digital)}');
    }
    sb.writeln();
    sb.writeln('_Generated by Chatori Finance_');
    return sb.toString();
  }

  /// Plain-text monthly P&L suitable for WhatsApp sharing.
  static String buildPlText({
    required DateTime month,
    required List<Bucket> revenue,
    required List<Bucket> cogs,
    required List<Bucket> operating,
  }) {
    int sum(List<Bucket> l) => l.fold(0, (s, b) => s + b.paise);
    final totalRevenue = sum(revenue);
    final totalCogs = sum(cogs);
    final totalOperating = sum(operating);
    final gross = totalRevenue - totalCogs;
    final net = gross - totalOperating;
    String pct(int part) => totalRevenue == 0
        ? '—'
        : '${(part / totalRevenue * 100).toStringAsFixed(1)}%';

    final sb = StringBuffer();
    sb.writeln('*P&L — ${DateFormat('MMMM yyyy').format(month)}*');
    sb.writeln();
    sb.writeln('REVENUE');
    for (final b in revenue) {
      sb.writeln('  ${b.label}: ${Money.format(b.paise)}');
    }
    sb.writeln('  = Total Revenue: ${Money.format(totalRevenue)}');
    sb.writeln();
    sb.writeln('COST OF GOODS SOLD');
    for (final b in cogs) {
      sb.writeln('  ${b.label}: ${Money.format(b.paise)}');
    }
    sb.writeln('  = Total COGS: ${Money.format(totalCogs)}');
    sb.writeln('  = GROSS PROFIT: ${Money.format(gross)} (${pct(gross)})');
    sb.writeln('  Food cost: ${pct(totalCogs)}');
    sb.writeln();
    sb.writeln('OPERATING EXPENSES');
    for (final b in operating) {
      sb.writeln('  ${b.label}: ${Money.format(b.paise)}');
    }
    sb.writeln('  = Total Operating: ${Money.format(totalOperating)}');
    sb.writeln();
    sb.writeln('*= NET PROFIT: ${Money.format(net)} (${pct(net)})*');
    sb.writeln();
    sb.writeln('_Generated by Chatori Finance_');
    return sb.toString();
  }

  /// Snapshot of current stock. Quantity is a plain number in the item's
  /// unit (so Excel can total it), with the unit in its own column. Value
  /// and avg cost are included only when [valueByItem] is supplied (owner).
  static String buildStockOnHandCsv(
    List<StockOnHand> items, {
    Map<String, StockValue>? valueByItem,
  }) {
    final showValue = valueByItem != null;
    final rows = <List<Object?>>[
      [
        'Item',
        'Category',
        'On hand',
        'Unit',
        if (showValue) 'Value (₹)',
        if (showValue) 'Avg cost (₹ per unit)',
        'Last updated',
      ],
      for (final s in items)
        [
          s.name,
          s.category ?? '',
          Quantity.fromMilli(s.onHandMilli, s.unit),
          s.displayUnit,
          if (showValue)
            valueByItem[s.itemId] == null
                ? ''
                : Money.toRupees(valueByItem[s.itemId]!.valuePaise),
          if (showValue)
            valueByItem[s.itemId] == null
                ? ''
                : Money.toRupees(
                    valueByItem[s.itemId]!.avgCostPerUnitPaise(s.unit)),
          s.lastMovedAt == null
              ? ''
              : _dateFmt.format(s.lastMovedAt!.toLocal()),
        ],
    ];
    return Csv().encode(rows);
  }

  /// Full movement ledger — every in/out, for auditing.
  static String buildStockMovementsCsv(List<StockActivity> activity) {
    final rows = <List<Object?>>[
      const ['Date', 'Item', 'Movement', 'Quantity', 'Reason', 'Note'],
      for (final a in activity)
        [
          _dateFmt.format(a.createdAt),
          a.itemName,
          a.type.label,
          Quantity.format(a.qtyMilli, a.dimension), // signed, e.g. "−1.5 kg"
          a.reason ?? '',
          a.note ?? '',
        ],
    ];
    return Csv().encode(rows);
  }

  /// Consumption + wastage for the month, per item.
  static String buildConsumptionCsv(List<ConsumptionRow> rows) {
    final out = <List<Object?>>[
      const ['Item', 'Consumed', 'Wasted', 'Unit'],
      for (final r in rows)
        [
          r.name,
          Quantity.fromMilli(r.consumedMilli,
              Quantity.defaultUnitFor(r.dimension)),
          Quantity.fromMilli(
              r.wastedMilli, Quantity.defaultUnitFor(r.dimension)),
          Quantity.defaultUnitFor(r.dimension).symbol,
        ],
    ];
    return Csv().encode(out);
  }

  /// Monthly P&L as a flat CSV: one row per category, plus totals.
  static String buildPlCsv({
    required List<Bucket> revenue,
    required List<Bucket> cogs,
    required List<Bucket> operating,
  }) {
    int sum(List<Bucket> l) => l.fold(0, (s, b) => s + b.paise);
    final tRev = sum(revenue), tCogs = sum(cogs), tOp = sum(operating);
    final rows = <List<Object?>>[
      const ['Section', 'Category', 'Amount (₹)'],
      for (final b in revenue) ['Revenue', b.label, Money.toRupees(b.paise)],
      ['Revenue', 'TOTAL REVENUE', Money.toRupees(tRev)],
      for (final b in cogs) ['COGS', b.label, Money.toRupees(b.paise)],
      ['COGS', 'TOTAL COGS', Money.toRupees(tCogs)],
      ['', 'GROSS PROFIT', Money.toRupees(tRev - tCogs)],
      for (final b in operating)
        ['Operating', b.label, Money.toRupees(b.paise)],
      ['Operating', 'TOTAL OPERATING', Money.toRupees(tOp)],
      ['', 'NET PROFIT', Money.toRupees(tRev - tCogs - tOp)],
    ];
    return Csv().encode(rows);
  }

  /// Writes CSV bytes to app cache and returns the path — for sharing.
  static Future<String> writeCsvToCache(String name, String csv) async {
    final dir = await getTemporaryDirectory();
    final safe = name.replaceAll(RegExp(r'[^A-Za-z0-9_\-.]'), '_');
    final file = File(p.join(dir.path, safe));
    await file.writeAsString(csv);
    return file.path;
  }

  /// Writes binary bytes (e.g. an .xlsx workbook) to app cache and returns
  /// the path — for sharing.
  static Future<String> writeBytesToCache(String name, List<int> bytes) async {
    final dir = await getTemporaryDirectory();
    final safe = name.replaceAll(RegExp(r'[^A-Za-z0-9_\-.]'), '_');
    final file = File(p.join(dir.path, safe));
    await file.writeAsBytes(bytes);
    return file.path;
  }

  /// Returns paise of advances still outstanding across all statuses.
  static int outstandingAdvances(List<Advance> advances) {
    var sum = 0;
    for (final a in advances) {
      if (a.status != 'closed') sum += a.outstandingPaise;
    }
    return sum;
  }
}
