import 'dart:io';

import 'package:csv/csv.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../core/money.dart';
import '../models/books.dart';
import '../models/txn.dart';

class ReportExporter {
  ReportExporter._();

  static final _dateFmt = DateFormat('yyyy-MM-dd HH:mm');

  /// Builds a CSV containing every field of every transaction.
  static String buildTransactionsCsv(Iterable<Txn> txns) {
    final rows = <List<Object?>>[
      const [
        'Date',
        'Type',
        'Category',
        'Amount (₹)',
        'Payment mode',
        'Party',
        'Notes',
        'Tag',
        'Source',
      ],
      for (final t in txns)
        [
          _dateFmt.format(t.occurredAt),
          t.type,
          t.category,
          Money.toRupees(t.amountPaise),
          t.paymentMode,
          t.partyName ?? '',
          t.notes ?? '',
          t.tag ?? '',
          t.source,
        ],
    ];
    return Csv().encode(rows);
  }

  /// Human-friendly monthly summary — pastes cleanly into WhatsApp / email.
  static String buildMonthlySummaryText({
    required DateTime month,
    required List<Txn> txns,
    required int salaryPaidPaise,
    required int advanceOutstandingPaise,
  }) {
    final title = DateFormat('MMMM yyyy').format(month);
    final income = txns.where((t) => t.isIncome).fold<int>(0, (s, t) => s + t.amountPaise);
    final expense = txns.where((t) => !t.isIncome).fold<int>(0, (s, t) => s + t.amountPaise);
    final net = income - expense;

    // Category breakdowns
    final expenseByCat = <String, int>{};
    final incomeByCat = <String, int>{};
    for (final t in txns) {
      final map = t.isIncome ? incomeByCat : expenseByCat;
      map.update(t.category, (v) => v + t.amountPaise, ifAbsent: () => t.amountPaise);
    }
    final expenseSorted = expenseByCat.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final incomeSorted = incomeByCat.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    // Payment mode split (expenses)
    var cash = 0;
    var digital = 0;
    for (final t in txns) {
      if (t.isIncome) continue;
      if (t.paymentMode == 'Cash') {
        cash += t.amountPaise;
      } else {
        digital += t.amountPaise;
      }
    }

    final sb = StringBuffer();
    sb.writeln('*Chatori Finance — $title*');
    sb.writeln();
    sb.writeln('💰 Income:   ${Money.format(income)}');
    sb.writeln('💸 Expenses: ${Money.format(expense)}');
    sb.writeln('📊 Net:      ${Money.format(net)}');
    sb.writeln();
    if (salaryPaidPaise > 0 || advanceOutstandingPaise > 0) {
      sb.writeln('👥 Salaries paid:      ${Money.format(salaryPaidPaise)}');
      sb.writeln('🧾 Advances outstanding: ${Money.format(advanceOutstandingPaise)}');
      sb.writeln();
    }
    if (incomeSorted.isNotEmpty) {
      sb.writeln('Income breakdown:');
      for (final e in incomeSorted) {
        sb.writeln('  • ${e.key}: ${Money.format(e.value)}');
      }
      sb.writeln();
    }
    if (expenseSorted.isNotEmpty) {
      sb.writeln('Top expenses:');
      for (final e in expenseSorted.take(6)) {
        sb.writeln('  • ${e.key}: ${Money.format(e.value)}');
      }
      sb.writeln();
    }
    if (expense > 0) {
      sb.writeln('Payment mix: '
          'Cash ${Money.format(cash)} · Digital ${Money.format(digital)}');
    }
    sb.writeln();
    sb.writeln('_Generated by Chatori Finance_');
    return sb.toString();
  }

  /// Writes CSV bytes to app cache and returns the path — for sharing.
  static Future<String> writeCsvToCache(String name, String csv) async {
    final dir = await getTemporaryDirectory();
    final safe = name.replaceAll(RegExp(r'[^A-Za-z0-9_\-.]'), '_');
    final file = File(p.join(dir.path, safe));
    await file.writeAsString(csv);
    return file.path;
  }

  /// Returns paise of advances still outstanding across all statuses.
  static int outstandingAdvances(List<Advance> advances) {
    var sum = 0;
    for (final a in advances) {
      if (a.status != 'closed') sum += a.outstandingPaise;
    }
    return sum;
  }
}
